// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volvo.Repository.Context;

namespace Volvo.Repository.Migrations
{
    [DbContext(typeof(VolvoContext))]
    partial class VolvoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Volvo.Domain.CaminhaoModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int>("AnoFabricao")
                        .HasColumnType("int")
                        .HasColumnName("ANO_FABRICACAO");

                    b.Property<int>("AnoModelo")
                        .HasColumnType("int")
                        .HasColumnName("ANO_MODELO");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("MODELO");

                    b.HasKey("Id");

                    b.ToTable("TB_VOLVO_CAMINHAO");
                });
#pragma warning restore 612, 618
        }
    }
}
